name: 'Github actions test'
on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Get wather report'
        run: bash ./weather.sh
