name: 'Github actions test'
on:
  push:
  schedule:
    - cron: '* * * * *'
runs-on: ubuntu-latest

jobs:
  job1:
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: 'Get wather report'
        run: bash ./weather.sh
